### ISSUE TITLE
Dependency Issues with IARS frontend

### ISSUE THREAD

**Issue by dane-stolsig** [Call-for-Code-for-Racial-Justice/Incident-Accuracy-Reporting-System#37]
Trying to run 'npm install' in Incident-Accuracy-Reporting-System/frontend throws several errors. Log is attached.
[2021-02-12T16_50_18_172Z-debug.log](https://github.com/Call-for-Code-for-Racial-Justice/Incident-Accuracy-Reporting-System/files/5973237/2021-02-12T16_50_18_172Z-debug.log)

**Comment by dane-stolsig** [comment]
Console output below, log doesn't seem all that helpful.


npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

> semantic-ui@2.4.2 install C:\Users\260107\Dev\AA\IARS\Incident-Accuracy-Reporting-System\frontend\node_modules\semantic-ui
> gulp install

fs.js:35
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (C:\Users\260107\Dev\AA\IARS\Incident-Accuracy-Reporting-System\frontend\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\260107\Dev\AA\IARS\Incident-Accuracy-Reporting-System\frontend\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\260107\Dev\AA\IARS\Incident-Accuracy-Reporting-System\frontend\node_modules\semantic-ui\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
npm WARN rollback Rolling back ansi-styles@2.2.1 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\Users\260107\Dev\AA\IARS\Incident-Accuracy-Reporting-System\frontend\node_modules\gulp-help\node_modules'
npm WARN rollback Rolling back map-stream@0.0.7 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\Users\260107\Dev\AA\IARS\Incident-Accuracy-Reporting-System\frontend\node_modules\gulp-print\node_modules'
npm WARN @carbon/charts@0.34.8 requires a peer of d3@>=5.0.0 <=5.14.2 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@8.0.0 requires a peer of webpack@^4.36.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.5.1 requires a peer of popper.js@^1.16.1 but none is installed. You must install peer dependencies yourself.
npm WARN vue2-leaflet@2.5.2 requires a peer of @types/leaflet@^1.5.7 but none is installed. You must install peer dependencies yourself.
npm WARN The package sass-loader is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! semantic-ui@2.4.2 install: `gulp install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the semantic-ui@2.4.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\260107\AppData\Roaming\npm-cache\_logs\2021-02-12T16_50_18_172Z-debug.log

**Comment by demilolu** [comment]
@swith004

**Comment by cafaray** [comment]
Hello @dane-stolsig 

I had a similar issue in my Windows machine, I'm not a nodejs expert, but a friend of mine advise me to install gulp

`npm i gulp -g`

Once installed, I didn't have issues. Hope this info help :)
