### ISSUE TITLE
Readme file - Section 5 Starting web application

### ISSUE THREAD

**Issue by cafaray** [Call-for-Code-for-Racial-Justice/Incident-Accuracy-Reporting-System#41]
In case starting the Frontend web application, to install dependencies modules I've installed gulp to get a successful installation. 

`npm i -g gulp`

In case stargting the Backend application, the README file indicates to change dir "backend" and execute `npm install`and `npm start`, but in this folder there isn't a package.json file and teh `server.js` or `app.js`. I guess the right location is:

`backend/SST-Audio`

¿could you please confirm?

**Comment by marcvelasco** [comment]
Hi just updating on this, I believe the original issue with gulp is a compatibility issue with the node version and gulp itself, any node version 12+ seems to not work with gulp 3.x, I believe what might have happened in the original user report was they installed a compatible version combination and then things worked but if they'd started with an earlier node version then things would have worked.  For reference: https://github.com/gulpjs/gulp/issues/2324
