### ISSUE TITLE
Readme File - Sections missing

### ISSUE THREAD

**Issue by cafaray** [Call-for-Code-for-Racial-Justice/Incident-Accuracy-Reporting-System#42]
In the main README file, section 6 and 7 are missing. From Section 5 jumps to Section 8.

**Comment by upkarlidder** [comment]
@cafaray, would you like to submit a PR on this during HacktoberFest?

FYI @demilolu

**Comment by demilolu** [comment]
Hi @konpyuta looks like this PR #78 addresses your issues here? If so, would you be interested in other contributing opps with our projects? Otherwise let's discuss any changes you may have here as recommendations.

**Comment by konpyuta** [comment]
This was originally brought up by @cafaray but it doesn't seem to be an issue anymore. The changes in PR #78 don't address it so it must have been changed in an earlier PR?
