### ISSUE TITLE
Add issues and feature template

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/Incident-Accuracy-Reporting-System#47]
Add issues and feature template. 

Example - https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/tree/main/.github/ISSUE_TEMPLATE

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by demilolu** [comment]
this issue has been completed
