### ISSUE TITLE
Epic - Mobile app upload 

### ISSUE THREAD

**Issue by asojoabiola** [Call-for-Code-for-Racial-Justice/Incident-Accuracy-Reporting-System#49]
**Features/Capabilities** 
     ios and android app support
     evidence upload
     upload eyewitness account

**Technical Requirements**
     mobile UI
     live streaming

**Roles Needed**
     Designers ux/ui
     Mobile App Developer
     A data protection person/reviewer
     Upload reviewer

Leveraging what other project have done

**Comment by nitekon1** [comment]
Similar issue being worked under https://github.com/Call-for-Code-for-Racial-Justice/Incident-Accuracy-Reporting-System/issues/96.
