### ISSUE TITLE
Clean up repo - remove base package.json files

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/Incident-Accuracy-Reporting-System#67]
### Background on the problem the feature will solve/improved user experience
The base directory contains a package.json and lock file that are not required.

### Describe the solution you'd like
Remove the files from the base repo

### Tasks 
Remove the files from the base repo

### Acceptance Criteria 
The files are removed.

**Comment by gibrankasif** [comment]
Can this task be assigned to me? @upkarlidder

**Comment by gibrankasif** [comment]
@upkarlidder I think this issue is missing the claimed label. 😅
